export const ADD_STAFF = 'ADD_STAFF';
export const DELETE_STAFF = 'DELETE_STAFF';
export const DELETE_STAFF_LOADING = 'DELETE_STAFF_LOADING';
export const UPDATE_STAFF = 'UPDATE_STAFF';
export const GET_STAFFS = 'GET_STAFFS';
export const STAFFS_LOADING = 'STAFFS_LOADING';
export const STAFFS_FAILED = 'STAFFS_FAILED';

export const GET_DEPARTMENTS = 'GET_DEPARTMENTS';
export const DEPARTMENTS_LOADING = 'DEPARTMENTS_LOADING';
export const DEPARTMENTS_FAILED = 'DEPARTMENTS_FAILED';

export const GET_SALARY = 'GET_SALARY';
export const SALARY_LOADING = 'SALARY_LOADING';
export const SALARY_FAILED = 'SALARY_FAILED';